FROM quay.io/openshiftio/fabric8-analytics-f8a-pypi-insights:latest

LABEL MAINTAINER="Aagam Shah <aagam@redhat.com>"

# --------------------------------------------------------------------------------------------------
# copy testing source code and scripts into root dir /
# --------------------------------------------------------------------------------------------------
ADD ./training/ /training
ADD ./tests/ /tests
ADD ./.git/ /.git
ADD ./tests/scripts/entrypoint-test.sh /entrypoint-test.sh
RUN chmod 0777 /entrypoint-test.sh

ENV PYTHONPATH=/
ENV USE_CLOUD_SERVICES="false"

RUN pip3 install git+https://github.com/fabric8-analytics/fabric8-analytics-rudra#egg=rudra
RUN pip3 install pytest pytest-cov radon==2.4.0 faker mock

# --------------------------------------------------------------------------------------------------
# RUN THE UNIT TESTS
# --------------------------------------------------------------------------------------------------
ENTRYPOINT ["/entrypoint-test.sh"]
